/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MyComponent as SlickButton
} from './components/slick-button/slick-button';

declare global {
  interface HTMLSlickButtonElement extends SlickButton, HTMLElement {
  }
  var HTMLSlickButtonElement: {
    prototype: HTMLSlickButtonElement;
    new (): HTMLSlickButtonElement;
  };
  interface HTMLElementTagNameMap {
    "slick-button": HTMLSlickButtonElement;
  }
  interface ElementTagNameMap {
    "slick-button": HTMLSlickButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "slick-button": JSXElements.SlickButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface SlickButtonAttributes extends HTMLAttributes {
      disabled?: boolean;
    }
  }
}


import {
  SlickMultiSelectOption as SlickMultiselectOption
} from './components/slick-multiselect-option/slick-multiselect-option';

declare global {
  interface HTMLSlickMultiselectOptionElement extends SlickMultiselectOption, HTMLElement {
  }
  var HTMLSlickMultiselectOptionElement: {
    prototype: HTMLSlickMultiselectOptionElement;
    new (): HTMLSlickMultiselectOptionElement;
  };
  interface HTMLElementTagNameMap {
    "slick-multiselect-option": HTMLSlickMultiselectOptionElement;
  }
  interface ElementTagNameMap {
    "slick-multiselect-option": HTMLSlickMultiselectOptionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "slick-multiselect-option": JSXElements.SlickMultiselectOptionAttributes;
    }
  }
  namespace JSXElements {
    export interface SlickMultiselectOptionAttributes extends HTMLAttributes {
      id?: string;
      name?: string;
      value?: string;
    }
  }
}


import {
  SlickMultiSelect as SlickMultiselect
} from './components/slick-multiselect/slick-multiselect';

declare global {
  interface HTMLSlickMultiselectElement extends SlickMultiselect, HTMLElement {
  }
  var HTMLSlickMultiselectElement: {
    prototype: HTMLSlickMultiselectElement;
    new (): HTMLSlickMultiselectElement;
  };
  interface HTMLElementTagNameMap {
    "slick-multiselect": HTMLSlickMultiselectElement;
  }
  interface ElementTagNameMap {
    "slick-multiselect": HTMLSlickMultiselectElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "slick-multiselect": JSXElements.SlickMultiselectAttributes;
    }
  }
  namespace JSXElements {
    export interface SlickMultiselectAttributes extends HTMLAttributes {
      name?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
